const wordList = [
  { word: "serendipity", hint: "Finding something good without looking for it" },
  { word: "nebulous", hint: "Vague, unclear" },
  { word: "mellifluous", hint: "Sweet or musical sounding" },
  { word: "ephemeral", hint: "Short-lived, transient" },
  { word: "resilience", hint: "Ability to bounce back from adversity" },
  { word: "esoteric", hint: "Understood by only a small number of people" },
  { word: "paradox", hint: "Seemingly contradictory statement that may be true" },
  { word: "ubiquitous", hint: "Present everywhere, pervasive" },
  { word: "ineffable", hint: "Too great or extreme to be expressed or described in words" },
  { word: "ostentatious", hint: "Showy, flamboyant" },
  { word: "serenity", hint: "Peaceful calmness" },
  { word: "indomitable", hint: "Impossible to subdue or defeat" },
  { word: "eloquent", hint: "Fluent or persuasive in speaking or writing" },
  { word: "capricious", hint: "Impulsive, unpredictable" },
  { word: "panacea", hint: "Cure-all, solution for all problems" },
  { word: "vicarious", hint: "Experienced through another's actions" },
  { word: "alacrity", hint: "Cheerful readiness, eagerness" },
  { word: "quixotic", hint: "Idealistic but impractical" },
  { word: "veracity", hint: "Truthfulness, accuracy" },
  { word: "pernicious", hint: "Harmful, destructive" },
  { word: "luminous", hint: "Bright, shining" },
  { word: "insidious", hint: "Gradually causing harm" },
  { word: "incessant", hint: "Continuing without interruption" },
  { word: "precarious", hint: "Dangerously unstable" },
  { word: "ambivalent", hint: "Having mixed feelings or contradictory ideas" },
  { word: "mellowness", hint: "State of being pleasantly smooth or soft" },
  { word: "euphoria", hint: "Feeling of intense excitement and happiness" },
  { word: "ebullient", hint: "Cheerful and full of energy" },
  { word: "vestige", hint: "Trace or remnant of something that is disappearing or no longer exists" },
  { word: "surreptitious", hint: "Secretive, sneaky" },
  { word: "voracious", hint: "Having a huge appetite, insatiable" },
  { word: "palpable", hint: "Able to be touched or felt" },
  { word: "facetious", hint: "Treating serious issues with deliberately inappropriate humor" },
  { word: "penultimate", hint: "Second to last" },
  { word: "inscrutable", hint: "Impossible to understand or interpret" },
  { word: "sagacious", hint: "Having or showing keen mental discernment and good judgment" },
  { word: "magnanimous", hint: "Generous and forgiving" },
  { word: "querulous", hint: "Complaining in a petulant or whining manner" },
  { word: "melancholy", hint: "Feeling of pensive sadness, typically with no obvious cause" },
  { word: "myriad", hint: "Countless or extremely great in number" },
  { word: "rambunctious", hint: "Uncontrollably exuberant; boisterous" },
  { word: "ambiguous", hint: "Open to more than one interpretation" },
  { word: "cacophony", hint: "Harsh, discordant mixture of sounds" },
  { word: "superfluous", hint: "Exceeding what is necessary" },
  { word: "laconic", hint: "Using very few words" },
  { word: "inconspicuous", hint: "Not clearly visible or attracting attention" },
  { word: "equanimity", hint: "Mental calmness, composure" },
  { word: "solitude", hint: "State of being alone" },
  { word: "vicissitude", hint: "A change of circumstances or fortune, typically one that is unwelcome or unpleasant" },
  { word: "Mundane", hint: "Lacking interest or excitement; dull" },
  { word: "aplomb", hint: "Self-confidence or assurance, especially when in a demanding situation" },
  { word: "banal", hint: "Lacking in originality, boring" },
  { word: "benevolent", hint: "Well-meaning and kindly" },
  { word: "candid", hint: "Truthful and straightforward" },
  { word: "complacent", hint: "Showing smug or uncritical satisfaction with oneself or one's achievements" },
  { word: "deleterious", hint: "Causing harm or damage" },
  { word: "diatribe", hint: "A forceful and bitter verbal attack against someone or something" },
  { word: "eclectic", hint: "Deriving ideas, style, or taste from a broad and diverse range of sources" },
  { word: "gregarious", hint: "Fond of company; sociable" },
  { word: "haughty", hint: "Arrogantly superior and disdainful" },
  { word: "idiosyncratic", hint: "Peculiar or individual" },
  { word: "juxtaposition", hint: "The fact of two things being seen or placed close together with contrasting effect" },
  { word: "kinetic", hint: "Relating to or resulting from motion" },
  { word: "lugubrious", hint: "Looking or sounding sad and dismal" },
  { word: "meticulous", hint: "Showing great attention to detail; very careful and precise" },
  { word: "nadir", hint: "The lowest point in the fortunes of a person or organization" },
  { word: "obfuscate", hint: "Render obscure, unclear, or unintelligible" },
  { word: "paragon", hint: "A person or thing regarded as a perfect example of a particular quality" },
  { word: "quintessential", hint: "Representing the most perfect or typical example of a quality or class" },
  { word: "reclusive", hint: "Avoiding the company of other people; solitary" },
  { word: "sanctimonious", hint: "Making a show of being morally superior to other people" },
  { word: "tantamount", hint: "Equivalent in seriousness to; virtually the same as" },
  { word: "vernacular", hint: "The language or dialect spoken by the ordinary people in a particular country or region" },
  { word: "wistful", hint: "Having or showing a feeling of vague or regretful longing" },
  { word: "zealot", hint: "A person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals" },
  { word: "aberration", hint: "A departure from what is normal, usual, or expected, typically one that is unwelcome" },
  { word: "acumen", hint: "The ability to make good judgments and quick decisions, typically in a particular domain" },
  { word: "belligerent", hint: "Hostile and aggressive" },
  { word: "cacophony", hint: "A harsh, discordant mixture of sounds" },
  { word: "dilapidated", hint: "In a state of disrepair or ruin as a result of age or neglect" },
  { word: "egalitarian", hint: "Believing in or based on the principle that all people are equal and deserve equal rights and opportunities" },
  { word: "euphemism", hint: "A mild or indirect word or expression substituted for one considered to be too harsh or blunt when referring to something unpleasant or embarrassing" },
  { word: "fortuitous", hint: "Happening by accident or chance rather than design" },
  { word: "garrulous", hint: "Excessively talkative, especially on trivial matters" },
  { word: "hackneyed", hint: "Lacking significance through having been overused; unoriginal and trite" },
  { word: "iconoclast", hint: "A person who attacks cherished beliefs or institutions" },
  { word: "languid", hint: "(of a person, manner, or gesture) having or showing a disinclination for physical exertion or effort" },
  { word: "misanthrope", hint: "A person who dislikes humankind and avoids human society" },
  { word: "narcissistic", hint: "Having an excessive interest in or admiration of oneself and one's physical appearance" },
  { word: "pervasive", hint: "Especially of an unwelcome influence or physical effect) spreading widely throughout an area or a group of people" },
  { word: "rancorous", hint: "Characterized by bitterness or resentment" },
  { word: "sanguine", hint: "Optimistic or positive, especially in an apparently bad or difficult situation" },
  { word: "temerity", hint: "Excessive confidence or boldness; audacity" },
  { word: "unfettered", hint: "Release from restraint or inhibition" },
  { word: "vacillate", hint: "Alternate or waver between different opinions or actions; be indecisive" },
  { word: "winsome", hint: "Attractive or appealing in appearance or character" },
  { word: "zealous", hint: "Having or showing zeal" },
  { word: "abrogate", hint: "Repeal or do away with (a law, right, or formal agreement)" },
  { word: "acrimonious", hint: "Typified by or filled with anger or bitterness" },
  { word: "belie", hint: "Fail to give a true notion or impression of (something); disguise or contradict" },
  { word: "candor", hint: "The quality of being open and honest in expression; frankness" },
  { word: "decry", hint: "Publicly denounce" },
  { word: "edify", hint: "Instruct or improve (someone) morally or intellectually" },
  { word: "fallacious", hint: "Based on a mistaken belief" }
  // Add the rest of the words here...
];