const wordList = [
  {
    word: "Serendipity",
    hint: "Finding something good without looking for it",
  },
  { word: "Nebulous", hint: "Vague, unclear" },
  { word: "Mellifluous", hint: "Sweet or musical sounding" },
  { word: "Ephemeral", hint: "Short-lived, transient" },
  { word: "Resilience", hint: "Ability to bounce back from adversity" },
  { word: "Esoteric", hint: "Understood by only a small number of people" },
  {
    word: "Paradox",
    hint: "Seemingly contradictory statement that may be true",
  },
  { word: "Ubiquitous", hint: "Present everywhere, pervasive" },
  {
    word: "Ineffable",
    hint: "Too great or extreme to be expressed or described in words",
  },
  { word: "Ostentatious", hint: "Showy, flamboyant" },
  { word: "Serenity", hint: "Peaceful calmness" },
  { word: "Indomitable", hint: "Impossible to subdue or defeat" },
  { word: "Eloquent", hint: "Fluent or persuasive in speaking or writing" },
  { word: "Capricious", hint: "Impulsive, unpredictable" },
  { word: "Panacea", hint: "Cure-all, solution for all problems" },
  { word: "Vicarious", hint: "Experienced through another's actions" },
  { word: "Alacrity", hint: "Cheerful readiness, eagerness" },
  { word: "Quixotic", hint: "Idealistic but impractical" },
  { word: "Veracity", hint: "Truthfulness, accuracy" },
  { word: "Pernicious", hint: "Harmful, destructive" },
  { word: "Luminous", hint: "Bright, shining" },
  { word: "Insidious", hint: "Gradually causing harm" },
  { word: "Incessant", hint: "Continuing without interruption" },
  { word: "Precarious", hint: "Dangerously unstable" },
  { word: "Ambivalent", hint: "Having mixed feelings or contradictory ideas" },
  { word: "Mellowness", hint: "State of being pleasantly smooth or soft" },
  { word: "Euphoria", hint: "Feeling of intense excitement and happiness" },
  { word: "Ebullient", hint: "Cheerful and full of energy" },
  {
    word: "Vestige",
    hint: "Trace or remnant of something that is disappearing or no longer exists",
  },
  { word: "Surreptitious", hint: "Secretive, sneaky" },
  { word: "Voracious", hint: "Having a huge appetite, insatiable" },
  { word: "Palpable", hint: "Able to be touched or felt" },
  {
    word: "Ineffable",
    hint: "Too great or extreme to be expressed or described in words",
  },
  {
    word: "Facetious",
    hint: "Treating serious issues with deliberately inappropriate humor",
  },
  { word: "Penultimate", hint: "Second to last" },
  { word: "Inscrutable", hint: "Impossible to understand or interpret" },
  {
    word: "Sagacious",
    hint: "Having or showing keen mental discernment and good judgment",
  },
  { word: "Magnanimous", hint: "Generous and forgiving" },
  { word: "Querulous", hint: "Complaining in a petulant or whining manner" },
  {
    word: "Melancholy",
    hint: "Feeling of pensive sadness, typically with no obvious cause",
  },
  { word: "Myriad", hint: "Countless or extremely great in number" },
  { word: "Rambunctious", hint: "Uncontrollably exuberant; boisterous" },
  { word: "Ambiguous", hint: "Open to more than one interpretation" },
  { word: "Cacophony", hint: "Harsh, discordant mixture of sounds" },
  { word: "Superfluous", hint: "Exceeding what is necessary" },
  { word: "Laconic", hint: "Using very few words" },
  {
    word: "Inconspicuous",
    hint: "Not clearly visible or attracting attention",
  },
  { word: "Equanimity", hint: "Mental calmness, composure" },
  { word: "Solitude", hint: "State of being alone" },
  {
    word: "Vicissitude",
    hint: "A change of circumstances or fortune, typically one that is unwelcome or unpleasant",
  },
  {
    word: "Serendipity",
    hint: "Finding something good without looking for it",
  },
  { word: "Nebulous", hint: "Vague, unclear" },
  { word: "Mellifluous", hint: "Sweet or musical sounding" },
  { word: "Ephemeral", hint: "Short-lived, transient" },
  { word: "Resilience", hint: "Ability to bounce back from adversity" },
  { word: "Esoteric", hint: "Understood by only a small number of people" },
  {
    word: "Paradox",
    hint: "Seemingly contradictory statement that may be true",
  },
  { word: "Ubiquitous", hint: "Present everywhere, pervasive" },
  {
    word: "Ineffable",
    hint: "Too great or extreme to be expressed or described in words",
  },
  { word: "Ostentatious", hint: "Showy, flamboyant" },
  { word: "Serenity", hint: "Peaceful calmness" },
  { word: "Indomitable", hint: "Impossible to subdue or defeat" },
  { word: "Eloquent", hint: "Fluent or persuasive in speaking or writing" },
  { word: "Capricious", hint: "Impulsive, unpredictable" },
  { word: "Panacea", hint: "Cure-all, solution for all problems" },
  { word: "Vicarious", hint: "Experienced through another's actions" },
  { word: "Alacrity", hint: "Cheerful readiness, eagerness" },
  { word: "Quixotic", hint: "Idealistic but impractical" },
  { word: "Veracity", hint: "Truthfulness, accuracy" },
  { word: "Pernicious", hint: "Harmful, destructive" },
  { word: "Luminous", hint: "Bright, shining" },
  { word: "Insidious", hint: "Gradually causing harm" },
  { word: "Incessant", hint: "Continuing without interruption" },
  { word: "Precarious", hint: "Dangerously unstable" },
  { word: "Ambivalent", hint: "Having mixed feelings or contradictory ideas" },
  { word: "Mellowness", hint: "State of being pleasantly smooth or soft" },
  { word: "Euphoria", hint: "Feeling of intense excitement and happiness" },
  { word: "Ebullient", hint: "Cheerful and full of energy" },
  {
    word: "Vestige",
    hint: "Trace or remnant of something that is disappearing or no longer exists",
  },
  { word: "Surreptitious", hint: "Secretive, sneaky" },
  { word: "Voracious", hint: "Having a huge appetite, insatiable" },
  { word: "Palpable", hint: "Able to be touched or felt" },
  {
    word: "Ineffable",
    hint: "Too great or extreme to be expressed or described in words",
  },
  {
    word: "Facetious",
    hint: "Treating serious issues with deliberately inappropriate humor",
  },
  { word: "Penultimate", hint: "Second to last" },
  { word: "Inscrutable", hint: "Impossible to understand or interpret" },
  {
    word: "Sagacious",
    hint: "Having or showing keen mental discernment and good judgment",
  },
  { word: "Magnanimous", hint: "Generous and forgiving" },
  { word: "Querulous", hint: "Complaining in a petulant or whining manner" },
  {
    word: "Melancholy",
    hint: "Feeling of pensive sadness, typically with no obvious cause",
  },
  { word: "Myriad", hint: "Countless or extremely great in number" },
  { word: "Rambunctious", hint: "Uncontrollably exuberant; boisterous" },
  { word: "Ambiguous", hint: "Open to more than one interpretation" },
  { word: "Cacophony", hint: "Harsh, discordant mixture of sounds" },
  { word: "Superfluous", hint: "Exceeding what is necessary" },
  { word: "Laconic", hint: "Using very few words" },
  {
    word: "Inconspicuous",
    hint: "Not clearly visible or attracting attention",
  },
  { word: "Equanimity", hint: "Mental calmness, composure" },
  { word: "Solitude", hint: "State of being alone" },
  {
    word: "Vicissitude",
    hint: "A change of circumstances or fortune, typically one that is unwelcome or unpleasant",
  },
];

